trigger:
  - main

pool:
  name: 'Default'

steps:

- checkout: self

- task: TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: 'latest'

- task: TerraformCLI@2
  displayName: 'Terraform Init'
  inputs:
    command: 'init'

- task: TerraformCLI@2
  displayName: 'Terraform Validate'
  inputs:
    command: 'validate'

- task: TerraformCLI@2
  displayName: 'Terraform Plan'
  inputs:
    command: 'plan'
    environmentServiceNameAzureRM: 'keraj_svc'
    commandOptions: '-var-file=terraform.tfvars'